import test from 'node:test';
import assert from 'node:assert';
import { readFileSync } from 'node:fs';
import { getStandardRate } from '../dist/esm/index.js';

// test-vectors.csv (next to this file) is generated by scripts/sync-data.mjs at the repo root. The expected rates in it are
// worked out by a plain scan of the published data, NOT by any of the libraries, and the Python and Java test
// suites check an identical copy of the same file. So this is what keeps the three libraries giving identical answers: for
// every country, the day before, the day of and the day after every rate change, and a few fixed dates.
const lines = readFileSync(new URL('./test-vectors.csv', import.meta.url), 'utf-8').trim().split('\n').slice(1);

test('the shared vectors cover all 27 countries, each with its boundary days (a missing or truncated file must not pass silently)', () => {
  const perCountry = new Map();
  for (const line of lines) { const c = line.split(',')[0]; perCountry.set(c, (perCountry.get(c) ?? 0) + 1); }
  assert.strictEqual(perCountry.size, 27);
  // every country has at least its five fixed dates plus the day after its first window
  for (const [c, n] of perCountry) assert.ok(n >= 6, `${c} has only ${n} vectors`);
});

test('every shared vector gives the expected rate', () => {
  for (const line of lines) {
    const [country, date, expected] = line.split(',');
    assert.strictEqual(getStandardRate(country, date), Number(expected), `${country} on ${date}`);
  }
});
