// Generated by scripts/sync-data.mjs from https://duty27.com/data/eu-standard-vat-rates.json. Do not hand-edit: run ./build.sh data.
// Data licence: CC BY 4.0 (see DATA-LICENSE.md). Standard rates only. Source hash f983c25f6657810f.
package com.duty27.euvat;

/** The generated rate data. Package-private: use {@link EuVat}. */
final class Data {
    private Data() {}

    static final String AS_OF = "2026-10-04";
    static final String SOURCE_SHA256 = "f983c25f6657810f86fa85e24d527f1989314a55c9408e47f3d0c5515cbbcc33";

    /** {code, name} per country, sorted by code. */
    static final String[][] COUNTRIES = {
        {"AT", "Austria"},
        {"BE", "Belgium"},
        {"BG", "Bulgaria"},
        {"CY", "Cyprus"},
        {"CZ", "Czechia"},
        {"DE", "Germany"},
        {"DK", "Denmark"},
        {"EE", "Estonia"},
        {"EL", "Greece"},
        {"ES", "Spain"},
        {"FI", "Finland"},
        {"FR", "France"},
        {"HR", "Croatia"},
        {"HU", "Hungary"},
        {"IE", "Ireland"},
        {"IT", "Italy"},
        {"LT", "Lithuania"},
        {"LU", "Luxembourg"},
        {"LV", "Latvia"},
        {"MT", "Malta"},
        {"NL", "Netherlands"},
        {"PL", "Poland"},
        {"PT", "Portugal"},
        {"RO", "Romania"},
        {"SE", "Sweden"},
        {"SI", "Slovenia"},
        {"SK", "Slovakia"},
    };

    /** Per country (same order as COUNTRIES): effective-from date, rate, effective-from date, rate, ... */
    static final String[][] WINDOWS = {
        {"2016-01-01", "20"},
        {"2016-01-01", "21"},
        {"2016-01-01", "20"},
        {"2016-01-01", "19"},
        {"2016-01-01", "21"},
        {"2016-01-01", "19", "2020-07-01", "16", "2021-01-01", "19"},
        {"2016-01-01", "25"},
        {"2016-01-01", "20", "2024-01-01", "22", "2025-07-01", "24"},
        {"2016-01-01", "23", "2016-06-01", "24"},
        {"2016-01-01", "21"},
        {"2016-01-01", "24", "2024-09-01", "25.5"},
        {"2016-01-01", "20"},
        {"2016-01-01", "25"},
        {"2016-01-01", "27"},
        {"2016-01-01", "23", "2020-09-01", "21", "2021-03-01", "23"},
        {"2016-01-01", "22"},
        {"2016-01-01", "21"},
        {"2016-01-01", "17", "2023-01-01", "16", "2024-01-01", "17"},
        {"2016-01-01", "21"},
        {"2016-01-01", "18"},
        {"2016-01-01", "21"},
        {"2016-01-01", "23"},
        {"2016-01-01", "23"},
        {"2016-01-01", "20", "2017-01-01", "19", "2025-08-01", "21"},
        {"2016-01-01", "25"},
        {"2016-01-01", "22"},
        {"2016-01-01", "20", "2025-01-01", "23"},
    };
}
