package com.duty27.euvat;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;

/**
 * Checks the library against test-vectors.csv (a test resource), the expected answers shared by the Node, Python and Java
 * tests, each of which has an identical copy.
 *
 * <p>The file is generated by scripts/sync-data.mjs at the repository root. Its expected rates are worked out by a
 * plain scan of the published data, not by any library, so this is what keeps the three libraries giving identical
 * answers: for every country, the day before, the day of and the day after every rate change, and a few fixed dates.
 */
class SharedVectorsTest {

    /** A test resource, so it is found on the classpath wherever Maven or an IDE runs the tests from. */
    private static final String VECTORS = "/test-vectors.csv";

    @Test
    void theVectorsCoverAll27CountriesEachWithItsBoundaryDays() throws IOException {
        // a missing or truncated file must not pass silently
        Map<String, Integer> perCountry = new HashMap<>();
        for (String line : rows()) {
            perCountry.merge(line.split(",")[0], 1, Integer::sum);
        }
        assertEquals(27, perCountry.size());
        perCountry.forEach((country, count) -> assertTrue(count >= 6, country + " has only " + count + " vectors"));
    }

    @Test
    void everySharedVectorGivesTheExpectedRate() throws IOException {
        for (String line : rows()) {
            String[] cells = line.split(",");
            BigDecimal expected = new BigDecimal(cells[2]);
            BigDecimal actual = EuVat.getStandardRate(cells[0], cells[1]);
            assertEquals(0, expected.compareTo(actual), cells[0] + " on " + cells[1] + ": expected " + expected + " but got " + actual);
        }
    }

    /** Every line except the header. */
    private static List<String> rows() throws IOException {
        try (InputStream in = SharedVectorsTest.class.getResourceAsStream(VECTORS)) {
            assertNotNull(in, VECTORS + " is missing from the test resources");
            List<String> lines = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8)).lines().collect(Collectors.toList());
            return lines.subList(1, lines.size());
        }
    }
}
