// Generated by scripts/sync-data.mjs from https://duty27.com/data/eu-standard-vat-rates.json. Do not hand-edit: run ./build.sh data.
// Data licence: CC BY 4.0 (see DATA-LICENSE.md). Standard rates only. Source hash f983c25f6657810f.
export const DATA_AS_OF = "2026-10-04";
export const DATA_SOURCE_SHA256 = "f983c25f6657810f86fa85e24d527f1989314a55c9408e47f3d0c5515cbbcc33";
export const DATA = [
  {
    "code": "AT",
    "name": "Austria",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 20
      }
    ]
  },
  {
    "code": "BE",
    "name": "Belgium",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 21
      }
    ]
  },
  {
    "code": "BG",
    "name": "Bulgaria",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 20
      }
    ]
  },
  {
    "code": "CY",
    "name": "Cyprus",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 19
      }
    ]
  },
  {
    "code": "CZ",
    "name": "Czechia",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 21
      }
    ]
  },
  {
    "code": "DE",
    "name": "Germany",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 19
      },
      {
        "from": "2020-07-01",
        "rate": 16
      },
      {
        "from": "2021-01-01",
        "rate": 19
      }
    ]
  },
  {
    "code": "DK",
    "name": "Denmark",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 25
      }
    ]
  },
  {
    "code": "EE",
    "name": "Estonia",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 20
      },
      {
        "from": "2024-01-01",
        "rate": 22
      },
      {
        "from": "2025-07-01",
        "rate": 24
      }
    ]
  },
  {
    "code": "EL",
    "name": "Greece",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 23
      },
      {
        "from": "2016-06-01",
        "rate": 24
      }
    ]
  },
  {
    "code": "ES",
    "name": "Spain",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 21
      }
    ]
  },
  {
    "code": "FI",
    "name": "Finland",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 24
      },
      {
        "from": "2024-09-01",
        "rate": 25.5
      }
    ]
  },
  {
    "code": "FR",
    "name": "France",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 20
      }
    ]
  },
  {
    "code": "HR",
    "name": "Croatia",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 25
      }
    ]
  },
  {
    "code": "HU",
    "name": "Hungary",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 27
      }
    ]
  },
  {
    "code": "IE",
    "name": "Ireland",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 23
      },
      {
        "from": "2020-09-01",
        "rate": 21
      },
      {
        "from": "2021-03-01",
        "rate": 23
      }
    ]
  },
  {
    "code": "IT",
    "name": "Italy",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 22
      }
    ]
  },
  {
    "code": "LT",
    "name": "Lithuania",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 21
      }
    ]
  },
  {
    "code": "LU",
    "name": "Luxembourg",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 17
      },
      {
        "from": "2023-01-01",
        "rate": 16
      },
      {
        "from": "2024-01-01",
        "rate": 17
      }
    ]
  },
  {
    "code": "LV",
    "name": "Latvia",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 21
      }
    ]
  },
  {
    "code": "MT",
    "name": "Malta",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 18
      }
    ]
  },
  {
    "code": "NL",
    "name": "Netherlands",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 21
      }
    ]
  },
  {
    "code": "PL",
    "name": "Poland",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 23
      }
    ]
  },
  {
    "code": "PT",
    "name": "Portugal",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 23
      }
    ]
  },
  {
    "code": "RO",
    "name": "Romania",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 20
      },
      {
        "from": "2017-01-01",
        "rate": 19
      },
      {
        "from": "2025-08-01",
        "rate": 21
      }
    ]
  },
  {
    "code": "SE",
    "name": "Sweden",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 25
      }
    ]
  },
  {
    "code": "SI",
    "name": "Slovenia",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 22
      }
    ]
  },
  {
    "code": "SK",
    "name": "Slovakia",
    "windows": [
      {
        "from": "2016-01-01",
        "rate": 20
      },
      {
        "from": "2025-01-01",
        "rate": 23
      }
    ]
  }
] as const;
