// The one place that knows how to turn the published rate data into each library.
//
// Source: https://duty27.com/data/eu-standard-vat-rates.json (CC BY 4.0, standard rates only), kept in this
// repo as data/eu-standard-vat-rates.json. Everything generated from it, for every language, carries the
// same SOURCE_SHA256 (a hash of the rates themselves, not of file formatting), so it is checkable that all
// three libraries were built from the same data.
import { createHash } from 'node:crypto';

export const SOURCE_URL = 'https://duty27.com/data/eu-standard-vat-rates.json';
export const FIRST_DATE = '2016-01-01';
export const CODES = ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'];

export const validDate = (s) => {
  if (typeof s !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(s)) return false;
  const d = new Date(`${s}T00:00:00Z`);
  return !Number.isNaN(d.getTime()) && d.toISOString().slice(0, 10) === s; // an impossible day is an Invalid Date
};

export function validateSource(src) {
  if (!/creativecommons\.org\/licenses\/by\/4\.0/.test(src.license ?? '')) throw new Error(`unexpected licence: ${src.license}`);
  if (!/duty27\.com\/vat-rates\/history/.test(src.attribution ?? '')) throw new Error('attribution line missing from the source');
  const codes = (src.countries ?? []).map(c => c.code);
  if (new Set(codes).size !== codes.length) throw new Error('duplicate country code in the source');
  if (codes.length !== 27 || !CODES.every(c => codes.includes(c))) throw new Error(`expected 27 countries (the EU member states), got ${codes.length}`);
  for (const c of src.countries) {
    const w = c.windows ?? [];
    if (w.length === 0 || w[0].from !== FIRST_DATE) throw new Error(`${c.code}: the first window must start on ${FIRST_DATE}`);
    for (let i = 0; i < w.length; i++) {
      if (!validDate(w[i].from)) throw new Error(`${c.code}: bad date ${w[i].from}`);
      if (typeof w[i].rate !== 'number' || w[i].rate < 5 || w[i].rate > 30) throw new Error(`${c.code} ${w[i].from}: implausible rate ${w[i].rate}`);
      if (i > 0 && w[i].from <= w[i - 1].from) throw new Error(`${c.code}: windows must be in ascending date order`);
      if (i > 0 && w[i].rate === w[i - 1].rate) throw new Error(`${c.code} ${w[i].from}: repeats the previous rate`);
    }
  }
}

// Countries sorted by code, with only the fields the libraries use: the same view for every generator.
function canonical(src) {
  return [...src.countries]
    .sort((a, b) => a.code.localeCompare(b.code))
    .map(c => ({ code: c.code, name: c.country, windows: c.windows.map(w => ({ from: w.from, rate: w.rate })) }));
}

/** A hash of the rates themselves (not of formatting), shared by every generated file. */
export function sourceSha256(src) {
  return createHash('sha256').update(JSON.stringify(canonical(src))).digest('hex');
}

function header(src, asOf, commentStart, commentEnd = '') {
  return `${commentStart} Generated by scripts/sync-data.mjs from ${SOURCE_URL}. Do not hand-edit: run ./build.sh data.${commentEnd}\n` +
    `${commentStart} Data licence: CC BY 4.0 (see DATA-LICENSE.md). Standard rates only. Source hash ${sourceSha256(src).slice(0, 16)}.${commentEnd}\n`;
}

function checked(src, asOf) {
  validateSource(src);
  if (!validDate(asOf)) throw new Error(`bad as-of date ${asOf}`);
}

/** node/src/data.ts */
export function buildDataModule(src, asOf) {
  checked(src, asOf);
  return header(src, asOf, '//') +
    `export const DATA_AS_OF = ${JSON.stringify(asOf)};\n` +
    `export const DATA_SOURCE_SHA256 = ${JSON.stringify(sourceSha256(src))};\n` +
    `export const DATA = ${JSON.stringify(canonical(src), null, 2)} as const;\n`;
}

/** python/src/duty27_eu_vat/_data.py. Rates are strings so Python builds exact Decimals. */
export function buildPythonModule(src, asOf) {
  checked(src, asOf);
  const rows = canonical(src).map(c =>
    `    (${JSON.stringify(c.code)}, ${JSON.stringify(c.name)}, (${c.windows.map(w => `(${JSON.stringify(w.from)}, ${JSON.stringify(String(w.rate))})`).join(', ')},)),`);
  return header(src, asOf, '#') +
    `DATA_AS_OF = ${JSON.stringify(asOf)}\n` +
    `DATA_SOURCE_SHA256 = ${JSON.stringify(sourceSha256(src))}\n\n` +
    `# (code, name, ((effective_from, rate), ...))\nDATA = (\n${rows.join('\n')}\n)\n`;
}

/** java/src/main/java/com/duty27/euvat/Data.java. Rates are strings so Java builds exact BigDecimals. */
export function buildJavaClass(src, asOf) {
  checked(src, asOf);
  const cs = canonical(src);
  const q = JSON.stringify; // Java string literals use the same escapes for these values
  return header(src, asOf, '//') +
    `package com.duty27.euvat;\n\n` +
    `/** The generated rate data. Package-private: use {@link EuVat}. */\n` +
    `final class Data {\n    private Data() {}\n\n` +
    `    static final String AS_OF = ${q(asOf)};\n` +
    `    static final String SOURCE_SHA256 = ${q(sourceSha256(src))};\n\n` +
    `    /** {code, name} per country, sorted by code. */\n` +
    `    static final String[][] COUNTRIES = {\n${cs.map(c => `        {${q(c.code)}, ${q(c.name)}},`).join('\n')}\n    };\n\n` +
    `    /** Per country (same order as COUNTRIES): effective-from date, rate, effective-from date, rate, ... */\n` +
    `    static final String[][] WINDOWS = {\n${cs.map(c => `        {${c.windows.map(w => `${q(w.from)}, ${q(String(w.rate))}`).join(', ')}},`).join('\n')}\n    };\n}\n`;
}

const addDays = (iso, n) => { const d = new Date(`${iso}T00:00:00Z`); d.setUTCDate(d.getUTCDate() + n); return d.toISOString().slice(0, 10); };

/**
 * test-vectors.csv (one identical copy in each language's test folder): expected answers for every language's tests, worked out here by a plain scan of the
 * data and not by any library: for every country, the day before, the day of and the day after each change,
 * plus the first day, a leap day, today-ish and a far-future date.
 */
export function buildVectors(src) {
  validateSource(src);
  const lines = ['country,date,rate'];
  const rateOn = (windows, day) => { let r = windows[0].rate; for (const w of windows) { if (w.from <= day) r = w.rate; } return r; };
  for (const c of canonical(src)) {
    const days = new Set([FIRST_DATE, '2016-12-31', '2020-02-29', '2026-10-04', '2035-01-01']);
    for (const w of c.windows) for (const n of [-1, 0, 1]) { const d = addDays(w.from, n); if (d >= FIRST_DATE) days.add(d); }
    for (const d of [...days].sort()) lines.push(`${c.code},${d},${rateOn(c.windows, d)}`);
  }
  return lines.join('\n') + '\n';
}
