import test from 'node:test';
import assert from 'node:assert';
import { buildDataModule, validateSource } from './data-lib.mjs';

// the shape published at https://duty27.com/data/eu-standard-vat-rates.json
const CODES = ['AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','EL','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE'];
const source = () => ({
  license: 'https://creativecommons.org/licenses/by/4.0/',
  attribution: 'Duty27 (https://duty27.com/vat-rates/history)',
  countries: CODES.map(code => ({ code, country: code === 'EL' ? 'Greece' : `Country ${code}`, windows: [{ from: '2016-01-01', rate: 20 }] })),
});

test('a valid source builds a deterministic module with the as-of date', () => {
  const a = buildDataModule(source(), '2026-10-04');
  const b = buildDataModule(source(), '2026-10-04');
  assert.strictEqual(a, b);
  assert.match(a, /export const DATA_AS_OF = "2026-10-04"/);
  assert.match(a, /Generated by scripts\/sync-data\.mjs/);
});

test('countries are sorted by code in the output so a reordered source gives the same file', () => {
  const s = source(); s.countries.reverse();
  assert.strictEqual(buildDataModule(s, '2026-10-04'), buildDataModule(source(), '2026-10-04'));
});

test('a bad source is rejected: missing country, wrong baseline, unsorted, repeated rate, implausible rate, wrong licence', () => {
  const mut = (f) => { const s = source(); f(s); return s; };
  assert.throws(() => validateSource(mut(s => s.countries.pop())), /27 countries/);
  assert.throws(() => validateSource(mut(s => { s.countries[0].windows[0].from = '2017-01-01'; })), /2016-01-01/);
  assert.throws(() => validateSource(mut(s => { s.countries[0].windows.push({ from: '2020-01-01', rate: 21 }, { from: '2019-01-01', rate: 22 }); })), /ascending/);
  assert.throws(() => validateSource(mut(s => { s.countries[0].windows.push({ from: '2020-01-01', rate: 20 }); })), /repeats/);
  assert.throws(() => validateSource(mut(s => { s.countries[0].windows[0].rate = 99; })), /implausible/);
  assert.throws(() => validateSource(mut(s => { s.license = 'https://example.com/all-rights-reserved'; })), /licen[cs]e/i);
  assert.throws(() => validateSource(mut(s => { s.countries[1].code = 'AT'; })), /duplicate|27 countries/);
});
