// Regenerates src/data.ts from the rate data Duty27 publishes at
// https://duty27.com/data/eu-standard-vat-rates.json (CC BY 4.0).
//
//   node scripts/update-data.mjs                      fetch the published file, write src/data.ts
//   node scripts/update-data.mjs --from ./file.json   read a local copy instead
//   node scripts/update-data.mjs --as-of 2026-10-04   the date the data was last compared with the
//                                                     published rates (default: today, UTC)
//   node scripts/update-data.mjs --check              change nothing; exit 1 if the published rates
//                                                     differ from this package (a release is due)
//
// The source is validated before anything is written, so a bad or truncated download can never
// become a release. Output is deterministic: the same source and as-of date give the same file.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

export const SOURCE_URL = 'https://duty27.com/data/eu-standard-vat-rates.json';
const FIRST_DATE = '2016-01-01';
const CODES = ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'];
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'data.ts');

const validDate = (s) => {
  if (typeof s !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(s)) return false;
  const d = new Date(`${s}T00:00:00Z`);
  return !Number.isNaN(d.getTime()) && d.toISOString().slice(0, 10) === s; // an impossible day is an Invalid Date
};

export function validateSource(src) {
  if (!/creativecommons\.org\/licenses\/by\/4\.0/.test(src.license ?? '')) throw new Error(`unexpected licence: ${src.license}`);
  if (!/duty27\.com\/vat-rates\/history/.test(src.attribution ?? '')) throw new Error('attribution line missing from the source');
  const codes = (src.countries ?? []).map(c => c.code);
  if (new Set(codes).size !== codes.length) throw new Error('duplicate country code in the source');
  if (codes.length !== 27 || !CODES.every(c => codes.includes(c))) throw new Error(`expected 27 countries (the EU member states), got ${codes.length}`);
  for (const c of src.countries) {
    const w = c.windows ?? [];
    if (w.length === 0 || w[0].from !== FIRST_DATE) throw new Error(`${c.code}: the first window must start on ${FIRST_DATE}`);
    for (let i = 0; i < w.length; i++) {
      if (!validDate(w[i].from)) throw new Error(`${c.code}: bad date ${w[i].from}`);
      if (typeof w[i].rate !== 'number' || w[i].rate < 5 || w[i].rate > 30) throw new Error(`${c.code} ${w[i].from}: implausible rate ${w[i].rate}`);
      if (i > 0 && w[i].from <= w[i - 1].from) throw new Error(`${c.code}: windows must be in ascending date order`);
      if (i > 0 && w[i].rate === w[i - 1].rate) throw new Error(`${c.code} ${w[i].from}: repeats the previous rate`);
    }
  }
}

export function buildDataModule(src, asOf) {
  validateSource(src);
  if (!validDate(asOf)) throw new Error(`bad as-of date ${asOf}`);
  const countries = [...src.countries]
    .sort((a, b) => a.code.localeCompare(b.code))
    .map(c => ({ code: c.code, name: c.country, windows: c.windows.map(w => ({ from: w.from, rate: w.rate })) }));
  return `// Generated by scripts/update-data.mjs from ${SOURCE_URL}. Do not hand-edit: run \`npm run data:update\`.\n` +
    `// Data licence: CC BY 4.0 (see DATA-LICENSE.md). Standard rates only.\n` +
    `export const DATA_AS_OF = ${JSON.stringify(asOf)};\n` +
    `export const DATA = ${JSON.stringify(countries, null, 2)} as const;\n`;
}

async function load(from) {
  if (from) return JSON.parse(readFileSync(from, 'utf-8'));
  const res = await fetch(SOURCE_URL, { signal: AbortSignal.timeout(30000) });
  if (!res.ok) throw new Error(`could not fetch ${SOURCE_URL}: HTTP ${res.status}`);
  return res.json();
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const args = process.argv.slice(2);
  const opt = (n, d) => (args.includes(n) ? args[args.indexOf(n) + 1] : d);
  const source = await load(opt('--from'));
  if (args.includes('--check')) {
    const current = readFileSync(OUT, 'utf-8');
    const asOf = current.match(/DATA_AS_OF = "(\d{4}-\d{2}-\d{2})"/)[1];
    if (buildDataModule(source, asOf) !== current) {
      console.error('The published rates differ from this package. Run `npm run data:update`, review the diff, and release.');
      process.exit(1);
    }
    console.log('This package matches the published rates.');
  } else {
    writeFileSync(OUT, buildDataModule(source, opt('--as-of', new Date().toISOString().slice(0, 10))));
    console.log(`Wrote ${OUT}`);
  }
}
