"""Checks the library against test-vectors.csv (next to this file), the expected answers shared by the Node, Python and
Java tests, each of which has an identical copy.

The file is generated by scripts/sync-data.mjs at the repo root. Its expected rates are worked out by a plain
scan of the published data, not by any library, so this is what keeps the three libraries giving identical
answers: for every country, the day before, the day of and the day after every rate change, and a few fixed dates.
"""
import csv
import unittest
from decimal import Decimal
from pathlib import Path

from duty27_eu_vat import get_standard_rate

VECTORS = Path(__file__).resolve().parent / "test-vectors.csv"


class SharedVectors(unittest.TestCase):
    def setUp(self):
        with VECTORS.open(newline="") as f:
            self.rows = list(csv.DictReader(f))

    def test_the_vectors_cover_all_27_countries_each_with_its_boundary_days(self):
        # a missing or truncated file must not pass silently
        per_country = {}
        for row in self.rows:
            per_country[row["country"]] = per_country.get(row["country"], 0) + 1
        self.assertEqual(len(per_country), 27)
        for country, count in per_country.items():
            self.assertGreaterEqual(count, 6, country)

    def test_every_shared_vector_gives_the_expected_rate(self):
        for row in self.rows:
            with self.subTest(country=row["country"], day=row["date"]):
                self.assertEqual(get_standard_rate(row["country"], row["date"]), Decimal(row["rate"]))


if __name__ == "__main__":
    unittest.main()
